In [44]:
import numpy as np
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
train, validate,test = np.split(a, [int(.7*len(a)), int(.8*len(a))])
train

array([0, 1, 2, 3, 4, 5, 6])

In [38]:
validate

array([7])

In [39]:
test

array([8, 9])